### ISSUE TITLE
name 'mergeGeometries' is not defined

### ISSUE THREAD

**Issue by leopinto718** [jamesfitton/cxr#1]
Hi, I am currently trying to run the section 3.6 of the waterOccurrence notebook but I got the following error: 

`C:\Python\cxr-master\waterOccurrence\cxrWaterOccurrence.py in make_col(date)
    110         mosaic = filtered.mosaic()
    111         mosaic = mosaic.set('system:time_start', date.millis(),
--> 112                             'system:footprint', mergeGeometries(filtered))
    113 
    114         mosaic = mosaic.rename(bands)

NameError: name 'mergeGeometries' is not defined`

It looks like this function mergeGeometries is not defined. I tried to look for this in the cxrWaterOccurrence.py but it was not there. Do you have any hints for me to discover the source of this error? 

Thanks!

**Comment by jamesfitton** [comment]
Hi,

Thanks for flagging this. I've not got time to update the code just at the minute but will do in the next few days. In the meantime, this is the function you're after! Any other issues let me know.

James

```
def mergeGeometries(collection):
    """ Merge the geometries of many images. Return ee.Geometry """
    imlist = collection.toList(collection.size())

    first = ee.Image(imlist.get(0))
    rest = imlist.slice(1)

    def wrap(img, ini):
        ini = ee.Geometry(ini)
        img = ee.Image(img)
        geom = img.geometry()
        union = geom.union(ini)
        return union.dissolve()

    return ee.Geometry(rest.iterate(wrap, first.geometry()))
```
